In [1]:
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns
from IPython.display import Markdown, display
def printmd(string):
    display(Markdown(string))

In [2]:
df_2018=pd.read_csv('2018_Financial_Data.csv')
df_2017=pd.read_csv('2017_Financial_Data.csv')
df_2016=pd.read_csv('2016_Financial_Data.csv')
df_2015=pd.read_csv('2015_Financial_Data.csv')
df_2014=pd.read_csv('2014_Financial_Data.csv')

In [3]:
df_2018['Year']=2018

In [4]:
df_2017['Year']=2017
df_2016['Year']=2016
df_2015['Year']=2015
df_2014['Year']=2014

In [5]:
expand_labels={'2019 PRICE VAR [%]':'Next year PRICE VAR [%]'}
df_2018.rename(columns=expand_labels,inplace=True)

In [6]:
expand_labels={'2018 PRICE VAR [%]':'Next year PRICE VAR [%]'}
df_2017.rename(columns=expand_labels,inplace=True)

In [ ]:
expand_labels={'2017 PRICE VAR [%]':'Next year PRICE VAR [%]'}
df_2016.rename(columns=expand_labels,inplace=True)

In [ ]:
expand_labels={'2016 PRICE VAR [%]':'Next year PRICE VAR [%]'}
df_2015.rename(columns=expand_labels,inplace=True)

In [ ]:
expand_labels={'2015 PRICE VAR [%]':'Next year PRICE VAR [%]'}
df_2014.rename(columns=expand_labels,inplace=True)

In [ ]:
frames = [df_2018, df_2017, df_2016,df_2015,df_2014]

result = pd.concat(frames,sort=False)

In [ ]:
result

In [ ]:
expand_labels1={'Unnamed: 0':'Company Name'}
result.rename(columns=expand_labels1,inplace=True)

In [ ]:
result_new=result.reset_index()
result_new

In [ ]:
list2=['Company Name',
 'Revenue',
 'Revenue per Share', 
 'priceToSalesRatio',
'priceSalesRatio',
 'Price to Sales Ratio',
 'Revenue Growth',
 '10Y Revenue Growth (per Share)',
 '5Y Revenue Growth (per Share)',
 '3Y Revenue Growth (per Share)',

 'Cost of Revenue',

 'Gross Profit',
'Gross Margin',
 'grossProfitMargin',
 'Gross Profit Growth', 

 'Operating Expenses',
 'R&D Expenses',
 'SG&A Expense',
 

 'SG&A to Revenue',
  'R&D to Revenue',

 'R&D Expense Growth',
 'SG&A Expenses Growth',


'Operating Income',
 'operatingProfitMargin',
 'Operating Income Growth',









 'Other comprehensive income',

 'Income Quality',

'EBITDA',
'EBITDA Margin',

'Depreciation & Amortization',

 'EBIT',
 'EBIT Margin',
 'ebitperRevenue',
 'eBITperRevenue',
 'ebtperEBIT',
 'niperEBT',
 'EBIT Growth',


 'Interest Expense',



'Earnings before Tax',
 'Earnings Before Tax Margin',
 'pretaxProfitMargin',
 'nIperEBT',
 'eBTperEBIT',



 'Income Tax Expense',
 'effectiveTaxRate',











 'Consolidated Income',
 'Net Income - Non-Controlling int',
 'Net Income - Discontinued ops',
 'Net Income Com',
 'Net Income',
 'netProfitMargin',
'Net Income per Share',
 'Net Income Growth',
 '10Y Net Income Growth (per Share)',
 '5Y Net Income Growth (per Share)',
 '3Y Net Income Growth (per Share)',

 'Profit Margin',
  'Net Profit Margin',


 'EPS',
 'EPS Growth',
 'Weighted Average Shs Out',
 'Weighted Average Shares Growth',

 'EPS Diluted', 
  'EPS Diluted Growth',
  'Weighted Average Shs Out (Dil)',
  'Weighted Average Shares Diluted Growth',



 'Earnings Yield',
 'priceEarningsRatio',
 'priceEarningsToGrowthRatio',
 'PE ratio',  


 'ROIC',
  'ROE',
 'returnOnEquity',
'returnOnAssets',
 'Return on Tangible Assets',
 'returnOnCapitalEmployed',


      
          
 'Preferred Dividends',  

 'dividendYield',
 'Dividend Yield', 

 'Dividend per Share', 
 'Dividends per Share Growth',
 '10Y Dividend per Share Growth (per Share)',
 '5Y Dividend per Share Growth (per Share)',
 '3Y Dividend per Share Growth (per Share)',


 'payoutRatio',
  'Payout Ratio', 
  'dividendPayoutRatio',





'Cash and cash equivalents',
 'Short-term investments',
 'Cash and short-term investments',
 'Receivables',
 'Receivables growth',
 'Inventories',
 'Inventory Growth',
 'Total current assets',
  'Net Current Asset Value',

 'Property, Plant & Equipment Net',
 'Goodwill and Intangible Assets',
'Intangibles to Total Assets',
 'Long-term investments',
 'Tax assets',
 'Total non-current assets',

 'Other Assets',
 'Total assets',

 'Asset Growth', 

'Tangible Asset Value',
     

 'Payables',
 'Short-term debt',  
 'Tax Liabilities',    
 'Deferred revenue',  
 'Total current liabilities',     


 'Long-term debt',
 'longtermDebtToCapitalization',
 'Total non-current liabilities',

 'Deposit Liabilities',   
 'Other Liabilities', 
 'Total liabilities',








 'Retained earnings (deficit)',
 'Total shareholders equity',
 'Shareholders Equity per Share',
 '10Y Shareholders Equity Growth (per Share)',
  '5Y Shareholders Equity Growth (per Share)',
  '3Y Shareholders Equity Growth (per Share)',


 'Investments', 
'Invested Capital',
'Total debt',
 'totalDebtToCapitalization',
'Net Debt',
 'Net Debt to EBITDA',

'debtRatio', 
 'debtEquityRatio',
 'Debt to Equity',
 'Debt to Assets',

 'Debt Growth',

  'Interest Debt per Share',     



 'Book Value per Share',
 'Tangible Book Value per Share',


'priceBookValueRatio',
 'priceToBookRatio',
 'PB ratio',
 'PTB ratio',

 'Book Value per Share Growth',





  'Stock-based compensation',
 'Stock-based compensation to Revenue',
  'Working Capital', 
 '10Y Operating CF Growth (per Share)',
  '5Y Operating CF Growth (per Share)',
  '3Y Operating CF Growth (per Share)',


 'Acquisitions and disposals',
 'Investment purchases and sales',
 'Investing Cash flow',


 'Issuance (repayment) of debt',
 'Issuance (buybacks) of shares',
 'Dividend payments',
 'Financing Cash Flow',


 'Effect of forex changes on cash',


 'Net cash flow / Change in cash', 
 'cashPerShare',
  'Cash per Share',
 'Operating Cash Flow',
'operatingCashFlowSalesRatio',
 'operatingCashFlowPerShare',
 'Operating Cash Flow per Share',
  'Operating Cash Flow growth',
 'priceToOperatingCashFlowsRatio',
  'Capital Expenditure',
 'Capex to Operating Cash Flow',
 'Capex to Revenue',
 'Capex to Depreciation',
'Capex per Share',
'Free Cash Flow',
 'Free Cash Flow margin', 
  'Free Cash Flow Yield',
'freeCashFlowPerShare',
 'Free Cash Flow per Share',
 'freeCashFlowOperatingCashFlowRatio',  
 'Free Cash Flow growth',
 'priceToFreeCashFlowsRatio',
'priceCashFlowRatio',


  'Average Receivables',
 'Receivables Turnover',
 'Days Sales Outstanding',
 'daysOfSalesOutstanding',



 'Average Payables',
  'Payables Turnover',
 'payablesTurnover',
 'Days Payables Outstanding',
 'daysOfPayablesOutstanding',

 'Average Inventory',
 'Inventory Turnover',
 'inventoryTurnover',
'Days of Inventory on Hand',
 'daysOfInventoryOutstanding',

 'fixedAssetTurnover',
 'assetTurnover',


 'currentRatio',
 'Current ratio',
 'quickRatio',
 'cashRatio',


 'operatingCycle',
  'cashConversionCycle', 






 'interestCoverage',    
 'cashFlowCoverageRatios',   
 'shortTermCoverageRatios', 
'capitalExpenditureCoverageRatios',
 'dividendpaidAndCapexCoverageRatios',
 'Interest Coverage',

     
'cashFlowToDebtRatio',
'POCF ratio',
 'PFCF ratio',







 'Market Cap',
  'Net Cash/Marketcap', 

 'Enterprise Value',
 'enterpriseValueMultiple',
 'Enterprise Value over EBITDA',
 'EV to Operating cash flow',
 'EV to Free cash flow', 
 'EV to Sales',




  'priceFairValue',                   
        
 
  'Graham Number',
  'Graham Net-Net',     
  'companyEquityMultiplier',




  'Sector',
 'Next year PRICE VAR [%]',
 'Class', 'Year']

In [ ]:
#result=result[list2]

# Balance sheet

In [138]:
df_balance_1=pd.read_csv("null from alpha vantage/balance revenue/null_value_revenue_balance_sheet_batch1.csv")
df_balance_2=pd.read_csv("null from alpha vantage/balance revenue/null_value_balance_sheet_batch2.csv")
df_balance_3=pd.read_csv("null from alpha vantage/balance revenue/null_value_balance_sheet_batch3.csv")

In [139]:
df_balance_4=pd.read_csv("null from alpha vantage/left/balance sheet/balance_left_batch1.csv")
df_balance_5=pd.read_csv("null from alpha vantage/left/balance sheet/balance_left_batch2.csv")
df_balance_6=pd.read_csv("null from alpha vantage/left/balance sheet/balance_left_batch3.csv")
df_balance_7=pd.read_csv("null from alpha vantage/left/balance sheet/balance_left_batch4.csv")
df_balance_8=pd.read_csv("null from alpha vantage/left/balance sheet/balance_left_batch5.csv")
df_balance_9=pd.read_csv("null from alpha vantage/left/balance sheet/balance_left_batch6.csv")
df_balance_10=pd.read_csv("null from alpha vantage/left/balance sheet/balance_left_batch7.csv")

In [140]:
frames_balance = [df_balance_1, df_balance_2, df_balance_3,df_balance_4,df_balance_5,df_balance_6,df_balance_7,df_balance_8,df_balance_9,df_balance_10]

balance = pd.concat(frames_balance,sort=False)

In [141]:
balance

,Unnamed: 0,fiscalDateEnding,reportedCurrency,totalAssets,intangibleAssets,earningAssets,otherCurrentAssets,totalLiabilities,totalShareholderEquity,deferredLongTermLiabilities,...,totalNonCurrentLiabilities,negativeGoodwill,warrants,preferredStockRedeemable,capitalSurplus,liabilitiesAndShareholderEquity,cashAndShortTermInvestments,accumulatedDepreciation,commonStockSharesOutstanding,company name
0,0,2019-12-31,USD,2.59035e+09,None,315166000,248016000,2.34312e+09,2.47223e+08,None,...,None,None,None,None,12234000,None,None,None,2000000,HIFS
1,1,2018-12-31,USD,2.40859e+09,None,355127000,292552000,2.19601e+09,2.12576e+08,None,...,None,None,None,None,11863000,None,None,None,2000000,HIFS
2,2,2017-12-31,USD,2.2846e+09,None,407772000,357975000,2.09844e+09,1.86158e+08,None,...,None,None,None,None,11750000,None,None,None,2000000,HIFS
3,3,2016-12-31,USD,2.0146e+09,None,366756000,325356000,1.85358e+09,1.61024e+08,None,...,None,None,None,None,11575000,None,None,None,2000000,HIFS
4,4,2015-12-31,USD,1.76853e+09,None,320674000,261907000,1.63051e+09,1.38015e+08,None,...,None,None,None,None,11052000,None,None,None,2000000,HIFS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2124,0,2019-12-31,USD,66728864,860087,None,4547036,11204469,55524395,None,...,5345497,None,None,None,19192394,66728864,43481781,None,11765875,IRMD
2125,1,2018-12-31,USD,48442258,832519,None,8244594,6496525,41945733,None,...,1807005,None,None,None,15317335,48442258,28027688,None,10989111,IRMD
2126,2,2017-12-31,USD,39012534,885502,None,776736,6081657,32930877,2003685,...,2003685,None,None,None,12623181,39012534,26341099,None,10596566,IRMD
2127,3,2016-12-31,USD,37194484,918712,None,514720,5305359,31889125,1643478,...,1643478,None,None,None,12055188,37194484,25679392,None,10722675,IRMD
2128,4,2015-12-31,USD,35244207,175513,None,591925,3311182,31933025,415782,...,415782,None,None,None,19332023,35244207,26970318,None,11175125,IRMD

In [142]:
balance['Year'] = pd.DatetimeIndex(balance['fiscalDateEnding']).year

In [143]:
balance['fiscalDateEnding str']=balance['fiscalDateEnding'].astype(str)
balance['Key'] = balance[['company name', 'fiscalDateEnding str']].apply(lambda x: ' '.join(x), axis = 1)

In [144]:
balance.drop(['fiscalDateEnding str'],axis=1,inplace=True)

In [147]:
balance.set_index('Key',inplace=True)

In [148]:
for company in balance['company name'].unique() :
    for year in balance[balance['company name']==company]['Year']:
        date_max=balance[(balance['company name']==company)& (balance['Year']==year)]['fiscalDateEnding'].max()
        balance.drop(balance[(balance['company name']==company)& (balance['Year']==year)& (balance['fiscalDateEnding']!=date_max)].index,axis=0,inplace=True)

In [266]:
balance

,fiscalDateEnding,reportedCurrency,totalAssets,intangibleAssets,earningAssets,otherCurrentAssets,totalLiabilities,totalShareholderEquity,deferredLongTermLiabilities,otherCurrentLiabilities,...,warrants,preferredStockRedeemable,capitalSurplus,liabilitiesAndShareholderEquity,cashAndShortTermInvestments,accumulatedDepreciation,commonStockSharesOutstanding,company name,Year,Month
Key,,,,,,,,,,,,,,,,,,,,,
HIFS 2019-12-31,2019-12-31,USD,2.59035e+09,None,315166000,248016000,2.34312e+09,2.47223e+08,None,None,...,None,None,12234000,None,None,None,2000000,HIFS,2019,12
HIFS 2018-12-31,2018-12-31,USD,2.40859e+09,None,355127000,292552000,2.19601e+09,2.12576e+08,None,None,...,None,None,11863000,None,None,None,2000000,HIFS,2018,12
HIFS 2017-12-31,2017-12-31,USD,2.2846e+09,None,407772000,357975000,2.09844e+09,1.86158e+08,None,None,...,None,None,11750000,None,None,None,2000000,HIFS,2017,12
HIFS 2016-12-31,2016-12-31,USD,2.0146e+09,None,366756000,325356000,1.85358e+09,1.61024e+08,None,None,...,None,None,11575000,None,None,None,2000000,HIFS,2016,12
HIFS 2015-12-31,2015-12-31,USD,1.76853e+09,None,320674000,261907000,1.63051e+09,1.38015e+08,None,None,...,None,None,11052000,None,None,None,2000000,HIFS,2015,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
IRMD 2019-12-31,2019-12-31,USD,66728864,860087,None,4547036,11204469,55524395,None,2020684,...,None,None,19192394,66728864,43481781,None,11765875,IRMD,2019,12
IRMD 2018-12-31,2018-12-31,USD,48442258,832519,None,8244594,6496525,41945733,None,1907205,...,None,None,15317335,48442258,28027688,None,10989111,IRMD,2018,12
IRMD 2017-12-31,2017-12-31,USD,39012534,885502,None,776736,6081657,32930877,2003685,1726142,...,None,None,12623181,39012534,26341099,None,10596566,IRMD,2017,12
IRMD 2016-12-31,2016-12-31,USD,37194484,918712,None,514720,5305359,31889125,1643478,1153780,...,None,None,12055188,37194484,25679392,None,10722675,IRMD,2016,12
IRMD 2015-12-31,2015-12-31,USD,35244207,175513,None,591925,3311182,31933025,415782,536924,...,None,None,19332023,35244207,26970318,None,11175125,IRMD,2015,12

In [182]:
balance.drop(['Unnamed: 0'],axis=1,inplace=True)

In [267]:
balance['Month'] = pd.DatetimeIndex(balance['fiscalDateEnding']).month

In [331]:
balance

,fiscalDateEnding,reportedCurrency,totalAssets,intangibleAssets,earningAssets,otherCurrentAssets,totalLiabilities,totalShareholderEquity,deferredLongTermLiabilities,otherCurrentLiabilities,...,liabilitiesAndShareholderEquity,cashAndShortTermInvestments,accumulatedDepreciation,commonStockSharesOutstanding,company name,Year,Month,Year_corrected,Year str,Key_test
Key,,,,,,,,,,,,,,,,,,,,,
HIFS 2019-12-31,2019-12-31,USD,2.59035e+09,None,315166000,248016000,2.34312e+09,2.47223e+08,None,None,...,None,None,None,2000000,HIFS,2019,12,2019,2019,HIFS 2019
HIFS 2018-12-31,2018-12-31,USD,2.40859e+09,None,355127000,292552000,2.19601e+09,2.12576e+08,None,None,...,None,None,None,2000000,HIFS,2018,12,2018,2018,HIFS 2018
HIFS 2017-12-31,2017-12-31,USD,2.2846e+09,None,407772000,357975000,2.09844e+09,1.86158e+08,None,None,...,None,None,None,2000000,HIFS,2017,12,2017,2017,HIFS 2017
HIFS 2016-12-31,2016-12-31,USD,2.0146e+09,None,366756000,325356000,1.85358e+09,1.61024e+08,None,None,...,None,None,None,2000000,HIFS,2016,12,2016,2016,HIFS 2016
HIFS 2015-12-31,2015-12-31,USD,1.76853e+09,None,320674000,261907000,1.63051e+09,1.38015e+08,None,None,...,None,None,None,2000000,HIFS,2015,12,2015,2015,HIFS 2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
IRMD 2019-12-31,2019-12-31,USD,66728864,860087,None,4547036,11204469,55524395,None,2020684,...,66728864,43481781,None,11765875,IRMD,2019,12,2019,2019,IRMD 2019
IRMD 2018-12-31,2018-12-31,USD,48442258,832519,None,8244594,6496525,41945733,None,1907205,...,48442258,28027688,None,10989111,IRMD,2018,12,2018,2018,IRMD 2018
IRMD 2017-12-31,2017-12-31,USD,39012534,885502,None,776736,6081657,32930877,2003685,1726142,...,39012534,26341099,None,10596566,IRMD,2017,12,2017,2017,IRMD 2017
IRMD 2016-12-31,2016-12-31,USD,37194484,918712,None,514720,5305359,31889125,1643478,1153780,...,37194484,25679392,None,10722675,IRMD,2016,12,2016,2016,IRMD 2016
IRMD 2015-12-31,2015-12-31,USD,35244207,175513,None,591925,3311182,31933025,415782,536924,...,35244207,26970318,None,11175125,IRMD,2015,12,2015,2015,IRMD 2015

In [291]:

for index in balance.index:
    if(balance.loc[index,'Month']>3):
        balance.loc[index,'Year_corrected']=balance.loc[index,'Year']
    else:
        balance.loc[index,'Year_corrected']=balance.loc[index,'Year']-1

In [294]:
balance.drop_duplicates(subset=['Year_corrected','company name'],keep='first',inplace=True)

In [295]:
balance['Year str']=balance['Year_corrected'].astype(str)
balance['Key_test'] = balance[['company name', 'Year str']].apply(lambda x: ' '.join(x), axis = 1)

In [296]:
balance['Key_test'].nunique()

12089

In [ ]:
balance.drop(['Year str','Key_test'],axis=1,inplace=True)

In [338]:
balance.drop(['Year'],axis=1,inplace=True)

In [349]:
balance.reset_index(inplace=True)

In [366]:
balance.drop(['Key','Month'],axis=1,inplace=True)

In [461]:
balance.replace(to_replace=['None'], value=np.nan, inplace=True)

In [468]:
balance.dropna(thresh=12,axis=0,inplace=True)

In [469]:
balance.fillna(0,inplace=True)

In [470]:
balance.to_csv("null from alpha vantage/balance.csv")

In [62]:
balance=pd.read_csv("null from alpha vantage/balance.csv")

# Income statement

In [310]:
df_income_1=pd.read_csv("null from alpha vantage/income revenue/null_value_revenue_income_statement_batch1.csv")
df_income_2=pd.read_csv("null from alpha vantage/income revenue/null_value_revenue_income_statement_batch2.csv")

In [311]:
df_income_3=pd.read_csv("null from alpha vantage/income asset/null_value_asset_income_statement_batch1.csv")
df_income_4=pd.read_csv("null from alpha vantage/income asset/null_value_asset_income_statement_batch2.csv")

In [312]:
df_income_5=pd.read_csv("null from alpha vantage/left/income/income_left_batch1.csv")
df_income_6=pd.read_csv("null from alpha vantage/left/income/income_left_batch2.csv")
df_income_7=pd.read_csv("null from alpha vantage/left/income/income_left_batch3.csv")
df_income_8=pd.read_csv("null from alpha vantage/left/income/income_left_batch4.csv")
df_income_9=pd.read_csv("null from alpha vantage/left/income/income_left_batch5.csv")
df_income_10=pd.read_csv("null from alpha vantage/left/income/income_left_batch6.csv")
df_income_11=pd.read_csv("null from alpha vantage/left/income/income_left_batch7.csv")
df_income_12=pd.read_csv("null from alpha vantage/left/income/income_left_batch8.csv")
df_income_13=pd.read_csv("null from alpha vantage/left/income/income_left_batch9.csv")
df_income_14=pd.read_csv("null from alpha vantage/left/income/income_left_batch10.csv")
df_income_15=pd.read_csv("null from alpha vantage/left/income/income_left_batch11.csv")
df_income_16=pd.read_csv("null from alpha vantage/left/income/income_left_batch12.csv")
df_income_17=pd.read_csv("null from alpha vantage/left/income/income_left_batch13.csv")

In [313]:
frames_income = [df_income_1, df_income_2, df_income_3,df_income_4,df_income_5,df_income_6,df_income_7,df_income_8,df_income_9,df_income_10,
df_income_11,df_income_12,df_income_13,df_income_14,df_income_15,df_income_16,df_income_17  ]                
        

income = pd.concat(frames_income,sort=False)

In [314]:
income['Year'] = pd.DatetimeIndex(income['fiscalDateEnding']).year

In [315]:
income

,Unnamed: 0,fiscalDateEnding,reportedCurrency,totalRevenue,totalOperatingExpense,costOfRevenue,grossProfit,ebit,netIncome,researchAndDevelopment,...,nonRecurring,otherItems,incomeTaxExpense,totalOtherIncomeExpense,discontinuedOperations,netIncomeFromContinuingOperations,netIncomeApplicableToCommonShares,preferredStockAndOtherAdjustments,company name,Year
0,0,2019-12-31,USD,75730000,19964000,None,74163000,None,3.8927e+07,None,...,None,None,14621000,-651000,None,38927000,38927000,None,HIFS,2019
1,1,2018-12-31,USD,64050000,19106000,0,62780000,0,3.0399e+07,None,...,None,None,12330000,-945000,None,30399000,30399000,None,HIFS,2018
2,2,2017-12-31,USD,65208000,18509000,18766000,63703000,0,2.5757e+07,None,...,None,None,18370000,-1.067e+06,None,25757000,25757000,None,HIFS,2017
3,3,2016-12-31,USD,60119000,18158000,14520000,58984000,0,2.3423e+07,None,...,None,None,16346000,-1.057e+06,None,23423000,23423000,None,HIFS,2016
4,4,2015-12-31,USD,51807000,18057000,11535000,51807000,0,1.9346e+07,None,...,None,None,13430000,-974000,None,19346000,19346000,None,HIFS,2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
355,0,2019-12-31,USD,38517141,21053575,8816161,29700980,9043317,9630959,1432719,...,None,None,-587642,7111,None,9630959,9630959,None,IRMD,2019
356,1,2018-12-31,USD,30438983,17223580,7211633,23227350,6197307,6303450,1517112,...,None,None,-106143,-44569,None,6303450,6303450,None,IRMD,2018
357,2,2017-12-31,USD,23081592,16226687,5569896,17511696,1396386,499764,1722564,...,None,None,896622,-11198,None,499764,499764,None,IRMD,2017
358,3,2016-12-31,USD,32496548,15421658,6154836,26341712,10952734,7214545,1347507,...,None,None,3738189,-93739,None,7214545,7214545,None,IRMD,2016
359,4,2015-12-31,USD,31593720,14240164,5840407,25753313,11634534,7529920,1764306,...,None,None,4104614,65952,None,7529920,7529920,None,IRMD,2015

In [316]:
income['fiscalDateEnding str']=income['fiscalDateEnding'].astype(str)
income['Key'] = income[['company name', 'fiscalDateEnding str']].apply(lambda x: ' '.join(x), axis = 1)

In [317]:
income.drop(['fiscalDateEnding str'],axis=1,inplace=True)

In [318]:
income.set_index('Key',inplace=True)

In [319]:
for company in income['company name'].unique() :
    for year in income[income['company name']==company]['Year']:
        date_max=income[(income['company name']==company)& (income['Year']==year)]['fiscalDateEnding'].max()
        income.drop(income[(income['company name']==company)& (income['Year']==year)& (income['fiscalDateEnding']!=date_max)].index,axis=0,inplace=True)

In [320]:
income.drop(['Unnamed: 0'],axis=1,inplace=True)

In [328]:
income

,fiscalDateEnding,reportedCurrency,totalRevenue,totalOperatingExpense,costOfRevenue,grossProfit,ebit,netIncome,researchAndDevelopment,effectOfAccountingCharges,...,discontinuedOperations,netIncomeFromContinuingOperations,netIncomeApplicableToCommonShares,preferredStockAndOtherAdjustments,company name,Year,Month,Year_corrected,Year str,Key_test
Key,,,,,,,,,,,,,,,,,,,,,
HIFS 2019-12-31,2019-12-31,USD,75730000,19964000,None,74163000,None,3.8927e+07,None,None,...,None,38927000,38927000,None,HIFS,2019,12,2019.0,2019.0,HIFS 2019.0
HIFS 2018-12-31,2018-12-31,USD,64050000,19106000,0,62780000,0,3.0399e+07,None,None,...,None,30399000,30399000,None,HIFS,2018,12,2018.0,2018.0,HIFS 2018.0
HIFS 2017-12-31,2017-12-31,USD,65208000,18509000,18766000,63703000,0,2.5757e+07,None,None,...,None,25757000,25757000,None,HIFS,2017,12,2017.0,2017.0,HIFS 2017.0
HIFS 2016-12-31,2016-12-31,USD,60119000,18158000,14520000,58984000,0,2.3423e+07,None,None,...,None,23423000,23423000,None,HIFS,2016,12,2016.0,2016.0,HIFS 2016.0
HIFS 2015-12-31,2015-12-31,USD,51807000,18057000,11535000,51807000,0,1.9346e+07,None,None,...,None,19346000,19346000,None,HIFS,2015,12,2015.0,2015.0,HIFS 2015.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
IRMD 2019-12-31,2019-12-31,USD,38517141,21053575,8816161,29700980,9043317,9630959,1432719,None,...,None,9630959,9630959,None,IRMD,2019,12,2019.0,2019.0,IRMD 2019.0
IRMD 2018-12-31,2018-12-31,USD,30438983,17223580,7211633,23227350,6197307,6303450,1517112,None,...,None,6303450,6303450,None,IRMD,2018,12,2018.0,2018.0,IRMD 2018.0
IRMD 2017-12-31,2017-12-31,USD,23081592,16226687,5569896,17511696,1396386,499764,1722564,None,...,None,499764,499764,None,IRMD,2017,12,2017.0,2017.0,IRMD 2017.0
IRMD 2016-12-31,2016-12-31,USD,32496548,15421658,6154836,26341712,10952734,7214545,1347507,None,...,None,7214545,7214545,None,IRMD,2016,12,2016.0,2016.0,IRMD 2016.0
IRMD 2015-12-31,2015-12-31,USD,31593720,14240164,5840407,25753313,11634534,7529920,1764306,None,...,None,7529920,7529920,None,IRMD,2015,12,2015.0,2015.0,IRMD 2015.0

In [322]:
income['Month'] = pd.DatetimeIndex(income['fiscalDateEnding']).month

In [323]:
for index in income.index:
    if(income.loc[index,'Month']>3):
        income.loc[index,'Year_corrected']=income.loc[index,'Year']
    else:
        income.loc[index,'Year_corrected']=income.loc[index,'Year']-1

In [327]:
income.drop_duplicates(subset=['Year_corrected','company name'],keep='first',inplace=True)

In [324]:
income['Year str']=income['Year_corrected'].astype(str)
income['Key_test'] = income[['company name', 'Year str']].apply(lambda x: ' '.join(x), axis = 1)

In [326]:
income['Key_test'].nunique()

12093

In [341]:
income.drop(['Year str','Key_test','Month','Year'],axis=1,inplace=True)

In [408]:
income

,fiscalDateEnding,reportedCurrency,totalRevenue,totalOperatingExpense,costOfRevenue,grossProfit,ebit,netIncome,researchAndDevelopment,effectOfAccountingCharges,...,nonRecurring,otherItems,incomeTaxExpense,totalOtherIncomeExpense,discontinuedOperations,netIncomeFromContinuingOperations,netIncomeApplicableToCommonShares,preferredStockAndOtherAdjustments,company name,Year_corrected
0,2019-12-31,USD,75730000,19964000,NaN,74163000,NaN,3.8927e+07,NaN,NaN,...,NaN,NaN,14621000,-651000,NaN,38927000,38927000,NaN,HIFS,2019.0
1,2018-12-31,USD,64050000,19106000,0,62780000,0,3.0399e+07,NaN,NaN,...,NaN,NaN,12330000,-945000,NaN,30399000,30399000,NaN,HIFS,2018.0
2,2017-12-31,USD,65208000,18509000,18766000,63703000,0,2.5757e+07,NaN,NaN,...,NaN,NaN,18370000,-1.067e+06,NaN,25757000,25757000,NaN,HIFS,2017.0
3,2016-12-31,USD,60119000,18158000,14520000,58984000,0,2.3423e+07,NaN,NaN,...,NaN,NaN,16346000,-1.057e+06,NaN,23423000,23423000,NaN,HIFS,2016.0
4,2015-12-31,USD,51807000,18057000,11535000,51807000,0,1.9346e+07,NaN,NaN,...,NaN,NaN,13430000,-974000,NaN,19346000,19346000,NaN,HIFS,2015.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12088,2019-12-31,USD,38517141,21053575,8816161,29700980,9043317,9630959,1432719,NaN,...,NaN,NaN,-587642,7111,NaN,9630959,9630959,NaN,IRMD,2019.0
12089,2018-12-31,USD,30438983,17223580,7211633,23227350,6197307,6303450,1517112,NaN,...,NaN,NaN,-106143,-44569,NaN,6303450,6303450,NaN,IRMD,2018.0
12090,2017-12-31,USD,23081592,16226687,5569896,17511696,1396386,499764,1722564,NaN,...,NaN,NaN,896622,-11198,NaN,499764,499764,NaN,IRMD,2017.0
12091,2016-12-31,USD,32496548,15421658,6154836,26341712,10952734,7214545,1347507,NaN,...,NaN,NaN,3738189,-93739,NaN,7214545,7214545,NaN,IRMD,2016.0
12092,2015-12-31,USD,31593720,14240164,5840407,25753313,11634534,7529920,1764306,NaN,...,NaN,NaN,4104614,65952,NaN,7529920,7529920,NaN,IRMD,2015.0

In [347]:
income.reset_index(inplace=True)

In [ ]:
income.drop(['Key'],axis=1,inplace=True)

In [431]:
income.replace(to_replace=['None'], value=np.nan, inplace=True)

In [429]:
#income=pd.read_csv("null from alpha vantage/income.csv")

In [432]:
income.dropna(thresh=8,axis=0,inplace=True)

In [434]:
income.drop(income[income['totalRevenue'].isna()].index,axis=0,inplace=True)

In [447]:
income.fillna(0,inplace=True)

In [448]:
income.to_csv("null from alpha vantage/income.csv")

In [63]:
income=pd.read_csv("null from alpha vantage/income.csv")

# cash flow

In [237]:
df_cash_1=pd.read_csv("null from alpha vantage/cash revenue/null_value_cash_flow_batch1.csv")

In [238]:
import pandas as pd
df_cash_2=pd.read_csv("null from alpha vantage/left/cash flow/left_cash_batch1.csv")
df_cash_3=pd.read_csv("null from alpha vantage/left/cash flow/left_cash_batch2.csv")
df_cash_4=pd.read_csv("null from alpha vantage/left/cash flow/left_cash_batch3.csv")
df_cash_5=pd.read_csv("null from alpha vantage/left/cash flow/left_cash_batch4.csv")
df_cash_6=pd.read_csv("null from alpha vantage/left/cash flow/left_cash_batch5.csv")
df_cash_7=pd.read_csv("null from alpha vantage/left/cash flow/left_cash_batch6.csv")
df_cash_8=pd.read_csv("null from alpha vantage/left/cash flow/left_cash_batch7.csv")
df_cash_9=pd.read_csv("null from alpha vantage/left/cash flow/left_cash_batch8.csv")

In [239]:
df_cash_10=pd.read_csv("null from alpha vantage/left/cash flow/ashish_cash.csv")
df_cash_11=pd.read_csv("null from alpha vantage/left/cash flow/cash_poonam_1.csv")
df_cash_12=pd.read_csv("null from alpha vantage/left/cash flow/cash_poonam_2.csv")

In [240]:
frames_cash = [df_cash_1, df_cash_2, df_cash_3,df_cash_4,df_cash_5,df_cash_6,df_cash_7,df_cash_8,df_cash_9,df_cash_10,
df_cash_11,df_cash_12  ]                
        

cash = pd.concat(frames_cash,sort=False)

In [188]:
cash

,Unnamed: 0,fiscalDateEnding,reportedCurrency,investments,changeInLiabilities,cashflowFromInvestment,otherCashflowFromInvestment,netBorrowings,cashflowFromFinancing,otherCashflowFromFinancing,...,stockSaleAndPurchase,changeInInventory,changeInAccountReceivables,changeInNetIncome,capitalExpenditures,changeInReceivables,changeInExchangeRate,changeInCashAndCashEquivalents,company name,Year_corrected
0,0,2019-12-31,USD,-219487000.0,0.0,-219487000.0,3806000.0,-101464000.0,142491000.0,248093000.0,...,0.0,0.0,-2222000.0,-5087000.0,647000.0,0.0,0,0.0,HIFS,2019.0
1,1,2018-12-31,USD,-187076000.0,0.0,-187076000.0,-1594000.0,27375000.0,91955000.0,68270000.0,...,0.0,0.0,-494000.0,3194000.0,1123000.0,0.0,0,0.0,HIFS,2018.0
2,2,2017-12-31,USD,-236072000.0,0.0,-236072000.0,-2044000.0,103790000.0,240928000.0,140592000.0,...,0.0,0.0,-920000.0,950000.0,256000.0,0.0,0,0.0,HIFS,2017.0
3,3,2016-12-31,USD,-182967000.0,0.0,-182967000.0,-4511000.0,72800000.0,219750000.0,149975000.0,...,213000.0,0.0,-129000.0,5000.0,98000.0,0.0,0,0.0,HIFS,2016.0
4,4,2015-12-31,USD,36814000.0,0.0,-132871000.0,-132222000.0,72811000.0,196439000.0,353184000.0,...,213000.0,0.0,0.0,-286000.0,649000.0,0.0,0,0.0,HIFS,2015.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11952,11955,2019-12-31,USD,-12083000.0,60673000.0,-33979000.0,-12083000.0,-1523000.0,-12099000.0,-296000.0,...,0.0,0.0,84557000.0,-25481000.0,21896000.0,32524000.0,0,102937000.0,UIHC,2019.0
11953,11956,2018-12-31,USD,-121574000.0,71001000.0,-125642000.0,-121574000.0,14055000.0,23369000.0,19582000.0,...,0.0,0.0,-251123000.0,9602000.0,4068000.0,-267544000.0,0,-92155000.0,UIHC,2018.0
11954,11957,2017-12-31,USD,-97391000.0,126289000.0,-7344000.0,95284000.0,127900000.0,118622000.0,-287000.0,...,0.0,0.0,-356963000.0,-5544000.0,5237000.0,-404290000.0,0,125587000.0,UIHC,2017.0
11955,11958,2016-12-31,USD,-13712000.0,98023000.0,-49757000.0,-32896000.0,55156000.0,49912000.0,-270000.0,...,0.0,0.0,-13050000.0,3674000.0,3149000.0,-66387000.0,0,65902000.0,UIHC,2016.0
11956,11959,2015-12-31,USD,-70566000.0,86368000.0,-67015000.0,14467000.0,-3422000.0,-7909000.0,-185000.0,...,0.0,0.0,-8577000.0,3724000.0,10916000.0,-25718000.0,0,23395000.0,UIHC,2015.0

In [241]:
cash['Year'] = pd.DatetimeIndex(cash['fiscalDateEnding']).year

In [242]:
cash['fiscalDateEnding str']=cash['fiscalDateEnding'].astype(str)
cash['Key'] = cash[['company name', 'fiscalDateEnding str']].apply(lambda x: ' '.join(x), axis = 1)

In [243]:
cash.drop(['fiscalDateEnding str'],axis=1,inplace=True)

In [244]:
cash.drop_duplicates(subset=['Key'],keep='last',inplace=True)

In [245]:
cash.set_index('Key',inplace=True)

In [247]:
for company in cash['company name'].unique() :
    for year in cash[cash['company name']==company]['Year']:
        date_max=cash[(cash['company name']==company)& (cash['Year']==year)]['fiscalDateEnding'].max()
        cash.drop(cash[(cash['company name']==company)& (cash['Year']==year)& (cash['fiscalDateEnding']!=date_max)].index,axis=0,inplace=True)

In [248]:
cash.drop(['Unnamed: 0'],axis=1,inplace=True)

In [357]:
cash

,fiscalDateEnding,reportedCurrency,investments,changeInLiabilities,cashflowFromInvestment,otherCashflowFromInvestment,netBorrowings,cashflowFromFinancing,otherCashflowFromFinancing,changeInOperatingActivities,...,capitalExpenditures,changeInReceivables,changeInExchangeRate,changeInCashAndCashEquivalents,company name,Year,Year str,Key_test,Month,Year_corrected
Key,,,,,,,,,,,,,,,,,,,,,
HIFS 2019-12-31,2019-12-31,USD,-219487000,0,-219487000,3806000,-101464000,142491000,248093000,181000,...,647000.0,None,None,None,HIFS,2019,2019.0,HIFS 2019.0,12,2019.0
HIFS 2018-12-31,2018-12-31,USD,-187076000,0,-187076000,-1594000,27375000,91955000,68270000,1521000,...,1123000.0,None,None,None,HIFS,2018,2018.0,HIFS 2018.0,12,2018.0
HIFS 2017-12-31,2017-12-31,USD,-236072000,0,-236072000,-2044000,103790000,240928000,140592000,397000,...,256000.0,None,None,None,HIFS,2017,2017.0,HIFS 2017.0,12,2017.0
HIFS 2016-12-31,2016-12-31,USD,-182967000,0,-182967000,-4511000,72800000,219750000,149975000,484000,...,98000.0,None,None,None,HIFS,2016,2016.0,HIFS 2016.0,12,2016.0
HIFS 2015-12-31,2015-12-31,USD,36814000,0,-132871000,-132222000,72811000,196439000,353184000,276000,...,649000.0,None,None,None,HIFS,2015,2015.0,HIFS 2015.0,12,2015.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
UIHC 2019-12-31,2019-12-31,USD,-12083000,60673000,-33979000,-12083000,-1523000,-12099000,-296000,124908000,...,21896000.0,32524000,None,102937000,UIHC,2019,2019.0,UIHC 2019.0,12,2019.0
UIHC 2018-12-31,2018-12-31,USD,-121574000,71001000,-125642000,-121574000,14055000,23369000,19582000,-81064000,...,4068000.0,-267544000,None,-92155000,UIHC,2018,2018.0,UIHC 2018.0,12,2018.0
UIHC 2017-12-31,2017-12-31,USD,-97391000,126289000,-7344000,95284000,127900000,118622000,-287000,-76941000,...,5237000.0,-404290000,None,125587000,UIHC,2017,2017.0,UIHC 2017.0,12,2017.0
UIHC 2016-12-31,2016-12-31,USD,-13712000,98023000,-49757000,-32896000,55156000,49912000,-270000,-13756000,...,3149000.0,-66387000,None,65902000,UIHC,2016,2016.0,UIHC 2016.0,12,2016.0
UIHC 2015-12-31,2015-12-31,USD,-70566000,86368000,-67015000,14467000,-3422000,-7909000,-185000,6805000,...,10916000.0,-25718000,None,23395000,UIHC,2015,2015.0,UIHC 2015.0,12,2015.0

In [351]:
cash['Month'] = pd.DatetimeIndex(cash['fiscalDateEnding']).month

In [352]:
for index in cash.index:
    if(cash.loc[index,'Month']>3):
        cash.loc[index,'Year_corrected']=cash.loc[index,'Year']
    else:
        cash.loc[index,'Year_corrected']=cash.loc[index,'Year']-1

In [356]:
cash.drop_duplicates(subset=['Year_corrected','company name'],keep='first',inplace=True)

In [353]:
cash['Year str']=cash['Year_corrected'].astype(str)
cash['Key_test'] = cash[['company name', 'Year str']].apply(lambda x: ' '.join(x), axis = 1)

In [354]:
cash['Key_test'].nunique()

11960

In [359]:
cash.drop(['Year str','Key_test','Month','Year'],axis=1,inplace=True)

In [368]:
cash.reset_index(inplace=True)

In [369]:
cash.drop(['Key'],axis=1,inplace=True)

In [439]:
cash.replace(to_replace=['None'], value=np.nan, inplace=True)

In [444]:
cash.dropna(thresh=5,axis=0,inplace=True)
#income.drop(income[income['totalRevenue'].isna()].index,axis=0,inplace=True)

In [445]:
cash.fillna(0,inplace=True)

In [446]:
cash.to_csv("null from alpha vantage/cash.csv")

In [64]:
cash=pd.read_csv("null from alpha vantage/cash.csv")

# Merge all 3 (income,cash,balance)

In [157]:
df_merge_1=pd.merge(balance,income,on=['company name','Year_corrected'],how='outer')



expand_labels={'reportedCurrency_x':'reportedCurrency_balance','fiscalDateEnding_x':'fiscalDateEnding_balance','fiscalDateEnding_y':'fiscalDateEnding_income',
               'reportedCurrency_y':'reportedCurrency_income'
        }

df_merge_1.rename(columns=expand_labels,inplace=True)


df_merge_2=pd.merge(df_merge_1,cash,on=['company name','Year_corrected'],how='outer')


expand_labels={'reportedCurrency':'reportedCurrency_cash','fiscalDateEnding':'fiscalDateEnding_cash'}

df_merge_2.rename(columns=expand_labels,inplace=True)

In [158]:
np.array(df_merge_2.columns)

array(['Unnamed: 0_x', 'fiscalDateEnding_balance',
       'reportedCurrency_balance', 'totalAssets', 'intangibleAssets',
       'earningAssets', 'otherCurrentAssets', 'totalLiabilities',
       'totalShareholderEquity', 'deferredLongTermLiabilities',
       'otherCurrentLiabilities', 'commonStock', 'retainedEarnings',
       'otherLiabilities', 'goodwill', 'otherAssets', 'cash',
       'totalCurrentLiabilities', 'shortTermDebt', 'currentLongTermDebt',
       'otherShareholderEquity', 'propertyPlantEquipment',
       'totalCurrentAssets', 'longTermInvestments', 'netTangibleAssets',
       'shortTermInvestments', 'netReceivables', 'longTermDebt',
       'inventory', 'accountsPayable', 'totalPermanentEquity',
       'additionalPaidInCapital', 'commonStockTotalEquity',
       'preferredStockTotalEquity', 'retainedEarningsTotalEquity',
       'treasuryStock', 'accumulatedAmortization',
       'otherNonCurrrentAssets', 'deferredLongTermAssetCharges',
       'totalNonCurrentAssets', 'capitalLeaseObligations',
       'totalLongTermDebt', 'otherNonCurrentLiabilities',
       'totalNonCurrentLiabilities', 'negativeGoodwill', 'warrants',
       'preferredStockRedeemable', 'capitalSurplus',
       'liabilitiesAndShareholderEquity', 'cashAndShortTermInvestments',
       'accumulatedDepreciation', 'commonStockSharesOutstanding',
       'company name', 'Year_corrected', 'Unnamed: 0_y', 'Unnamed: 0.1',
       'fiscalDateEnding_income', 'reportedCurrency_income',
       'totalRevenue', 'totalOperatingExpense', 'costOfRevenue',
       'grossProfit', 'ebit', 'netIncome_x', 'researchAndDevelopment',
       'effectOfAccountingCharges', 'incomeBeforeTax', 'minorityInterest',
       'sellingGeneralAdministrative', 'otherNonOperatingIncome',
       'operatingIncome', 'otherOperatingExpense', 'interestExpense',
       'taxProvision', 'interestIncome', 'netInterestIncome',
       'extraordinaryItems', 'nonRecurring', 'otherItems',
       'incomeTaxExpense', 'totalOtherIncomeExpense',
       'discontinuedOperations', 'netIncomeFromContinuingOperations',
       'netIncomeApplicableToCommonShares',
       'preferredStockAndOtherAdjustments', 'Unnamed: 0',
       'fiscalDateEnding_cash', 'reportedCurrency_cash', 'investments',
       'changeInLiabilities', 'cashflowFromInvestment',
       'otherCashflowFromInvestment', 'netBorrowings',
       'cashflowFromFinancing', 'otherCashflowFromFinancing',
       'changeInOperatingActivities', 'netIncome_y', 'changeInCash',
       'operatingCashflow', 'otherOperatingCashflow', 'depreciation',
       'dividendPayout', 'stockSaleAndPurchase', 'changeInInventory',
       'changeInAccountReceivables', 'changeInNetIncome',
       'capitalExpenditures', 'changeInReceivables',
       'changeInExchangeRate', 'changeInCashAndCashEquivalents'],
      dtype=object)

In [159]:
col_currency=[
       'totalAssets', 'intangibleAssets', 'earningAssets',
       'otherCurrentAssets', 'totalLiabilities', 'totalShareholderEquity',
       'deferredLongTermLiabilities', 'otherCurrentLiabilities',
        'retainedEarnings', 'otherLiabilities', 'goodwill',
       'otherAssets', 'cash', 'totalCurrentLiabilities', 'shortTermDebt',
       'currentLongTermDebt', 'otherShareholderEquity',
       'propertyPlantEquipment', 'totalCurrentAssets',
       'longTermInvestments', 'netTangibleAssets', 'shortTermInvestments',
       'netReceivables', 'longTermDebt', 'inventory', 'accountsPayable',
       'totalPermanentEquity', 'additionalPaidInCapital',
       'commonStockTotalEquity', 'preferredStockTotalEquity',
       'retainedEarningsTotalEquity', 
       'accumulatedAmortization', 'otherNonCurrrentAssets',
       'deferredLongTermAssetCharges', 'totalNonCurrentAssets',
       'capitalLeaseObligations', 'totalLongTermDebt',
       'otherNonCurrentLiabilities', 'totalNonCurrentLiabilities',
       'negativeGoodwill', 'warrants', 
       'capitalSurplus', 'liabilitiesAndShareholderEquity',
       'cashAndShortTermInvestments', 'accumulatedDepreciation',
       'totalRevenue', 'totalOperatingExpense', 'costOfRevenue',
       'grossProfit', 'ebit', 'netIncome_x', 'researchAndDevelopment',
       'effectOfAccountingCharges', 'incomeBeforeTax', 'minorityInterest',
       'sellingGeneralAdministrative', 'otherNonOperatingIncome',
       'operatingIncome', 'otherOperatingExpense', 'interestExpense',
       'taxProvision', 'interestIncome', 'netInterestIncome',
       'extraordinaryItems', 'nonRecurring', 'otherItems',
       'incomeTaxExpense', 'totalOtherIncomeExpense',
       'discontinuedOperations', 'netIncomeFromContinuingOperations',
       'netIncomeApplicableToCommonShares',
       'preferredStockAndOtherAdjustments',  'investments', 'changeInLiabilities',
       'cashflowFromInvestment', 'otherCashflowFromInvestment',
       'netBorrowings', 'cashflowFromFinancing',
       'otherCashflowFromFinancing', 'changeInOperatingActivities',
       'netIncome_y', 'changeInCash', 'operatingCashflow',
       'otherOperatingCashflow', 'depreciation', 'dividendPayout',
       'stockSaleAndPurchase', 'changeInInventory',
       'changeInAccountReceivables', 'changeInNetIncome',
       'capitalExpenditures', 'changeInReceivables',
       'changeInExchangeRate', 'changeInCashAndCashEquivalents']

In [160]:
currency=pd.read_csv("currency converter.csv")

In [161]:
currency

,Code,country,2020,2019,2018,2017,2016,2015,2014,2013,2012,2011,2010,2009
0,ARS,Argentine Peso,0.026558,0.026558,0.026558,0.053712,0.063080,0.077265,0.118131,0.118131,0.118131,0.118131,0.118131,0.118131
1,AUD,Australian Dollar,0.704578,0.704578,0.704578,0.781414,0.720150,0.729405,0.818124,0.818124,0.818124,0.818124,0.818124,0.818124
2,BRL,Brazilian Real,0.257670,0.257670,0.257670,0.301895,0.307201,0.252462,0.376276,0.376276,0.376276,0.376276,0.376276,0.376276
3,GBP,British Pound,1.276021,1.276021,1.276021,1.350291,1.233210,1.476337,1.558642,1.558642,1.558642,1.558642,1.558642,1.558642
4,CAD,Canadian Dollar,0.732902,0.732902,0.732902,0.795343,0.743859,0.722156,0.862737,0.862737,0.862737,0.862737,0.862737,0.862737
5,CLP,Chilean Peso,0.001441,0.001441,0.001441,0.001625,0.001495,0.001410,0.001651,0.001651,0.001651,0.001651,0.001651,0.001651
6,CNY,Chinese Yuan Renminbi,0.145384,0.145384,0.145384,0.153705,0.143995,0.153959,0.161117,0.161117,0.161117,0.161117,0.161117,0.161117
7,COP,Colombian Peso,0.000308,0.000308,0.000308,0.000335,0.000333,0.000315,0.000421,0.000421,0.000421,0.000421,0.000421,0.000421
8,DKK,Danish Krone,0.153435,0.153435,0.153435,0.161065,0.141517,0.145650,0.162657,0.162657,0.162657,0.162657,0.162657,0.162657
9,EUR,Euro,1.145548,1.145548,1.145548,1.199861,1.052255,1.086653,1.211023,1.211023,1.211023,1.211023,1.211023,1.211023
10,INR,Indian Rupee,0.014367,0.014367,0.014367,0.015662,0.014713,0.015105,0.015826,0.015826,0.015826,0.015826,0.015826,0.015826
11,IDR,Indonesian Rupiah,0.000070,0.000070,0.000070,0.000074,0.000074,0.000072,0.000081,0.000081,0.000081,0.000081,0.000081,0.000081
12,ILS,Israeli Shekel,0.267412,0.267412,0.267412,0.287191,0.259621,0.256649,0.256239,0.256239,0.256239,0.256239,0.256239,0.256239
13,JPY,Japanese Yen,0.009115,0.009115,0.009115,0.008876,0.008549,0.008312,0.008350,0.008350,0.008350,0.008350,0.008350,0.008350
14,MXN,Mexican Peso,0.050910,0.050910,0.050910,0.050666,0.048227,0.057973,0.067833,0.067833,0.067833,0.067833,0.067833,0.067833
15,NZD,New Zealand Dollar,0.670861,0.670861,0.670861,0.709580,0.692325,0.684219,0.780488,0.780488,0.780488,0.780488,0.780488,0.780488
16,RUB,Russian Ruble,0.014416,0.014416,0.014416,0.017320,0.016322,0.013609,0.017073,0.017073,0.017073,0.017073,0.017073,0.017073
17,ZAR,South African Rand,0.069515,0.069515,0.069515,0.080687,0.072795,0.064450,0.086600,0.086600,0.086600,0.086600,0.086600,0.086600
18,KRW,South Korean Won,0.000898,0.000898,0.000898,0.000938,0.000828,0.000850,0.000916,0.000916,0.000916,0.000916,0.000916,0.000916
19,SEK,Swedish Krona,0.112739,0.112739,0.112739,0.122196,0.109801,0.118414,0.128126,0.128126,0.128126,0.128126,0.128126,0.128126
20,CHF,Swiss Franc,1.016946,1.016946,1.016946,1.025927,0.980969,1.000280,1.007253,1.007253,1.007253,1.007253,1.007253,1.007253
21,TWD,Taiwan New Dollar,0.032663,0.032663,0.032663,0.033662,0.030840,0.030419,0.031635,0.031635,0.031635,0.031635,0.031635,0.031635
22,PEN,Peru,0.300000,0.300000,0.300000,0.300000,0.300000,0.300000,0.300000,0.300000,0.300000,0.300000,0.300000,0.300000
23,USD,USA,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [162]:
currency.set_index('Code',inplace=True)

In [163]:
def f1(x,y,z):
    if (x is not np.nan):
        return x
    elif(y is not np.nan):
        return y
    elif(z is not np.nan):
        return z

In [164]:
df_merge_2['currency']=df_merge_2.apply(lambda x: f1(x['reportedCurrency_balance'],x['reportedCurrency_cash'],x['reportedCurrency_income']),axis=1)



df_merge_2

,Unnamed: 0_x,fiscalDateEnding_balance,reportedCurrency_balance,totalAssets,intangibleAssets,earningAssets,otherCurrentAssets,totalLiabilities,totalShareholderEquity,deferredLongTermLiabilities,...,dividendPayout,stockSaleAndPurchase,changeInInventory,changeInAccountReceivables,changeInNetIncome,capitalExpenditures,changeInReceivables,changeInExchangeRate,changeInCashAndCashEquivalents,currency
0,0.0,2019-12-31,USD,2.590346e+09,0.0,315166000.0,248016000.0,2.343123e+09,247223000.0,0.0,...,-4352000.0,0.0,0.0,-2222000.0,-5087000.0,647000.0,0.0,0.0,0.0,USD
1,1.0,2018-12-31,USD,2.408587e+09,0.0,355127000.0,292552000.0,2.196011e+09,212576000.0,0.0,...,-3690000.0,0.0,0.0,-494000.0,3194000.0,1123000.0,0.0,0.0,0.0,USD
2,2.0,2017-12-31,USD,2.284599e+09,0.0,407772000.0,357975000.0,2.098441e+09,186158000.0,0.0,...,-3454000.0,0.0,0.0,-920000.0,950000.0,256000.0,0.0,0.0,0.0,USD
3,3.0,2016-12-31,USD,2.014599e+09,0.0,366756000.0,325356000.0,1.853575e+09,161024000.0,0.0,...,-3238000.0,213000.0,0.0,-129000.0,5000.0,98000.0,0.0,0.0,0.0,USD
4,4.0,2015-12-31,USD,1.768528e+09,0.0,320674000.0,261907000.0,1.630513e+09,138015000.0,0.0,...,-4556000.0,213000.0,0.0,0.0,-286000.0,649000.0,0.0,0.0,0.0,USD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12117,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,USD
12118,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,USD
12119,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,904476.0,0.0,0.0,0.0,0.0,AUD
12120,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,USD
12121,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,USD

In [165]:
df_merge_2.drop(df_merge_2[df_merge_2['currency']=='0'].index,axis=0,inplace=True)

In [166]:
np.array(df_merge_2.columns)

array(['Unnamed: 0_x', 'fiscalDateEnding_balance',
       'reportedCurrency_balance', 'totalAssets', 'intangibleAssets',
       'earningAssets', 'otherCurrentAssets', 'totalLiabilities',
       'totalShareholderEquity', 'deferredLongTermLiabilities',
       'otherCurrentLiabilities', 'commonStock', 'retainedEarnings',
       'otherLiabilities', 'goodwill', 'otherAssets', 'cash',
       'totalCurrentLiabilities', 'shortTermDebt', 'currentLongTermDebt',
       'otherShareholderEquity', 'propertyPlantEquipment',
       'totalCurrentAssets', 'longTermInvestments', 'netTangibleAssets',
       'shortTermInvestments', 'netReceivables', 'longTermDebt',
       'inventory', 'accountsPayable', 'totalPermanentEquity',
       'additionalPaidInCapital', 'commonStockTotalEquity',
       'preferredStockTotalEquity', 'retainedEarningsTotalEquity',
       'treasuryStock', 'accumulatedAmortization',
       'otherNonCurrrentAssets', 'deferredLongTermAssetCharges',
       'totalNonCurrentAssets', 'capitalLeaseObligations',
       'totalLongTermDebt', 'otherNonCurrentLiabilities',
       'totalNonCurrentLiabilities', 'negativeGoodwill', 'warrants',
       'preferredStockRedeemable', 'capitalSurplus',
       'liabilitiesAndShareholderEquity', 'cashAndShortTermInvestments',
       'accumulatedDepreciation', 'commonStockSharesOutstanding',
       'company name', 'Year_corrected', 'Unnamed: 0_y', 'Unnamed: 0.1',
       'fiscalDateEnding_income', 'reportedCurrency_income',
       'totalRevenue', 'totalOperatingExpense', 'costOfRevenue',
       'grossProfit', 'ebit', 'netIncome_x', 'researchAndDevelopment',
       'effectOfAccountingCharges', 'incomeBeforeTax', 'minorityInterest',
       'sellingGeneralAdministrative', 'otherNonOperatingIncome',
       'operatingIncome', 'otherOperatingExpense', 'interestExpense',
       'taxProvision', 'interestIncome', 'netInterestIncome',
       'extraordinaryItems', 'nonRecurring', 'otherItems',
       'incomeTaxExpense', 'totalOtherIncomeExpense',
       'discontinuedOperations', 'netIncomeFromContinuingOperations',
       'netIncomeApplicableToCommonShares',
       'preferredStockAndOtherAdjustments', 'Unnamed: 0',
       'fiscalDateEnding_cash', 'reportedCurrency_cash', 'investments',
       'changeInLiabilities', 'cashflowFromInvestment',
       'otherCashflowFromInvestment', 'netBorrowings',
       'cashflowFromFinancing', 'otherCashflowFromFinancing',
       'changeInOperatingActivities', 'netIncome_y', 'changeInCash',
       'operatingCashflow', 'otherOperatingCashflow', 'depreciation',
       'dividendPayout', 'stockSaleAndPurchase', 'changeInInventory',
       'changeInAccountReceivables', 'changeInNetIncome',
       'capitalExpenditures', 'changeInReceivables',
       'changeInExchangeRate', 'changeInCashAndCashEquivalents',
       'currency'], dtype=object)

In [167]:
def f2(x,y,z):
    if (z is not np.nan):
        return float(currency.loc[x,str(y)])*float(z)
    else:
        return np.nan

In [168]:
#df_merge_2[cols] = df_merge_2.apply(lambda x: f(x[cols], x[]), axis=1)

for cols in col_currency:
    df_merge_2[cols]=df_merge_2.apply(lambda x:f2(x['currency'],x['Year_corrected'],x[cols]),axis=1)

In [172]:
df_merge_2['Other Liabilities']=df_merge_2['otherLiabilities']+df_merge_2['otherCurrentLiabilities']+df_merge_2['otherNonCurrentLiabilities']+df_merge_2['deferredLongTermLiabilities']

In [173]:
df_merge_2['Goodwill and Intangible Assets']=df_merge_2['goodwill']+df_merge_2['intangibleAssets']

In [174]:
df_merge_2['Total debt']=df_merge_2['longTermDebt']+df_merge_2['shortTermDebt']

In [175]:
dict1={   'Company Name' : 'company name' ,
 'Revenue': 'totalRevenue',
 'Cost of Revenue' : 'costOfRevenue',
 'Gross Profit' : 'grossProfit' ,
 'Operating Expenses': 'totalOperatingExpense' ,
 'R&D Expenses' : 'researchAndDevelopment' ,
 'SG&A Expense' : 'sellingGeneralAdministrative',
 'Operating Income' : 'operatingIncome',
 'Depreciation & Amortization': 'depreciation',
 'EBIT' : 'ebit' ,
 'Interest Expense' :'interestExpense' ,
 'Earnings before Tax' :'incomeBeforeTax' ,
  'Income Tax Expense' : 'incomeTaxExpense',
 'Net Income - Discontinued ops' : 'discontinuedOperations' ,
 'Net Income Com' : 'netIncomeApplicableToCommonShares',
 'Net Income' : 'netIncome_x',
 'Weighted Average Shs Out': 'commonStockSharesOutstanding' ,
 'Preferred Dividends' : 'preferredStockAndOtherAdjustments',
 'Cash and cash equivalents' : 'cash' ,
 'Short-term investments' : 'shortTermInvestments' ,
 'Cash and short-term investments' : 'cashAndShortTermInvestments' ,
 'Receivables' : 'netReceivables' ,
 'Inventories' : 'inventory' ,
 'Total current assets':'totalCurrentAssets',
 'Property, Plant & Equipment Net' : 'propertyPlantEquipment' ,
 'Goodwill and Intangible Assets' : 'Goodwill and Intangible Assets',
 'Total non-current assets' : 'totalNonCurrentAssets' ,
 'Other Assets' : 'otherAssets' ,
 'Total assets' : 'totalAssets',
  'Payables' : 'accountsPayable' ,
   'Short-term debt' : 'shortTermDebt' ,
   'Total current liabilities' : 'totalCurrentLiabilities',
   'Long-term debt':'longTermDebt',
  'Total non-current liabilities' : 'totalNonCurrentLiabilities' ,
   'Other Liabilities':'Other Liabilities',
  'Total liabilities' : 'totalLiabilities' ,
   'Retained earnings (deficit)' : 'retainedEarnings' ,
   'Total shareholders equity' : 'totalShareholderEquity' ,
   'Investments' : 'longTermInvestments' ,
   'Total debt' : 'Total debt',
   'Investing Cash flow' : 'cashflowFromInvestment' ,
   'Dividend payments' : 'dividendPayout' ,
    'Financing Cash Flow' : 'cashflowFromFinancing' ,
     'Effect of forex changes on cash' : 'changeInExchangeRate' ,
    'Net cash flow / Change in cash':'changeInCashAndCashEquivalents',
    'Operating Cash Flow' : 'operatingCashflow',
   'Capital Expenditure' : 'capitalExpenditures',
    'Average Receivables' : 'netReceivables',
   'Average Payables' : 'accountsPayable' ,
    'Average Inventory' : 'inventory',
       'Depreciation & Amortization': 'depreciation',
       
     'Year' : 'Year_corrected' }

In [176]:
dict2={}
for a,b in dict1.items():
    dict2.update({b:a})

In [177]:
dict2

{'company name': 'Company Name',
 'totalRevenue': 'Revenue',
 'costOfRevenue': 'Cost of Revenue',
 'grossProfit': 'Gross Profit',
 'totalOperatingExpense': 'Operating Expenses',
 'researchAndDevelopment': 'R&D Expenses',
 'sellingGeneralAdministrative': 'SG&A Expense',
 'operatingIncome': 'Operating Income',
 'depreciation': 'Depreciation & Amortization',
 'ebit': 'EBIT',
 'interestExpense': 'Interest Expense',
 'incomeBeforeTax': 'Earnings before Tax',
 'incomeTaxExpense': 'Income Tax Expense',
 'discontinuedOperations': 'Net Income - Discontinued ops',
 'netIncomeApplicableToCommonShares': 'Net Income Com',
 'netIncome_x': 'Net Income',
 'commonStockSharesOutstanding': 'Weighted Average Shs Out',
 'preferredStockAndOtherAdjustments': 'Preferred Dividends',
 'cash': 'Cash and cash equivalents',
 'shortTermInvestments': 'Short-term investments',
 'cashAndShortTermInvestments': 'Cash and short-term investments',
 'netReceivables': 'Average Receivables',
 'inventory': 'Average Inventory',
 'totalCurrentAssets': 'Total current assets',
 'propertyPlantEquipment': 'Property, Plant & Equipment Net',
 'Goodwill and Intangible Assets': 'Goodwill and Intangible Assets',
 'totalNonCurrentAssets': 'Total non-current assets',
 'otherAssets': 'Other Assets',
 'totalAssets': 'Total assets',
 'accountsPayable': 'Average Payables',
 'shortTermDebt': 'Short-term debt',
 'totalCurrentLiabilities': 'Total current liabilities',
 'longTermDebt': 'Long-term debt',
 'totalNonCurrentLiabilities': 'Total non-current liabilities',
 'Other Liabilities': 'Other Liabilities',
 'totalLiabilities': 'Total liabilities',
 'retainedEarnings': 'Retained earnings (deficit)',
 'totalShareholderEquity': 'Total shareholders equity',
 'longTermInvestments': 'Investments',
 'Total debt': 'Total debt',
 'cashflowFromInvestment': 'Investing Cash flow',
 'dividendPayout': 'Dividend payments',
 'cashflowFromFinancing': 'Financing Cash Flow',
 'changeInExchangeRate': 'Effect of forex changes on cash',
 'changeInCashAndCashEquivalents': 'Net cash flow / Change in cash',
 'operatingCashflow': 'Operating Cash Flow',
 'capitalExpenditures': 'Capital Expenditure',
 'Year_corrected': 'Year'}

In [178]:
df_merge_2.rename(columns=dict2,inplace=True)

In [182]:
df_merge_2['Company Name'].unique()

array(['HIFS', 'FRC', 'COBZ', ..., 'PIY', 'JCO', 'OSBCP'], dtype=object)

In [180]:
df_merge_2.to_csv("null from alpha vantage/alpha_final.csv")

# enterprise value

In [29]:
ev1=pd.read_csv('null from alpha vantage/ev/company_ev_batch1.csv')
ev2=pd.read_csv('null from alpha vantage/ev/company_ev_batch2.csv')
ev3=pd.read_csv('null from alpha vantage/ev/company_ev_batch3.csv')
ev4=pd.read_csv('null from alpha vantage/ev/company_ev_batch4.csv')
ev5=pd.read_csv('null from alpha vantage/ev/company_ev_batch5.csv')
ev6=pd.read_csv('null from alpha vantage/ev/company_ev_batch6.csv')

In [30]:
frames_ev = [ev1, ev2, ev3,ev4,ev5,ev6]

ev = pd.concat(frames_ev,sort=False)

In [31]:
ev

,Unnamed: 0,symbol,date,stockPrice,numberOfShares,marketCapitalization,minusCashAndCashEquivalents,addTotalDebt,enterpriseValue
0,0,DNP,2019-10-31,12.75,300945540.0,3.837056e+09,29923890.0,996205290.0,4.803337e+09
1,1,DNP,2018-10-31,10.98,293197640.0,3.219310e+09,16950540.0,996100240.0,4.198460e+09
2,2,DNP,2017-10-31,11.35,287493950.0,3.263056e+09,35350560.0,995005850.0,4.222712e+09
3,3,DNP,2016-10-31,10.04,283655070.0,2.847897e+09,27143770.0,993911430.0,3.814665e+09
4,4,DNP,2015-10-31,9.43,279789380.0,2.638414e+09,41105260.0,996741810.0,3.594050e+09
...,...,...,...,...,...,...,...,...,...
1263,0,SPNE,2019-12-31,15.01,18977000.0,2.848448e+08,20199000.0,0.0,2.646458e+08
1264,1,SPNE,2018-12-31,14.83,15358000.0,2.277591e+08,24233000.0,0.0,2.035261e+08
1265,2,SPNE,2017-12-31,10.90,12426000.0,1.354434e+08,10788000.0,0.0,1.246554e+08
1266,3,SPNE,2016-12-31,7.20,11222000.0,8.079840e+07,14566000.0,4280000.0,7.051240e+07
1267,4,SPNE,2015-12-31,14.46,11139000.0,1.610699e+08,33429000.0,328000.0,1.279689e+08

In [32]:
ev['Year'] = pd.DatetimeIndex(ev['date']).year

In [33]:
ev['Month'] = pd.DatetimeIndex(ev['date']).month

In [34]:
ev['date str']=ev['date'].astype(str)
ev['Key'] = ev[['symbol', 'date str']].apply(lambda x: ' '.join(x), axis = 1)

In [35]:
ev.drop(['date str'],axis=1,inplace=True)

In [36]:
ev.set_index('Key',inplace=True)

In [37]:
for company in ev['symbol'].unique() :
    for year in ev[ev['symbol']==company]['Year']:
        date_max=ev[(ev['symbol']==company)& (ev['Year']==year)]['date'].max()
        ev.drop(ev[(ev['symbol']==company)& (ev['Year']==year)& (ev['date']!=date_max)].index,axis=0,inplace=True)

In [39]:
ev

,Unnamed: 0,symbol,date,stockPrice,numberOfShares,marketCapitalization,minusCashAndCashEquivalents,addTotalDebt,enterpriseValue,Year,Month
Key,,,,,,,,,,,
DNP 2019-10-31,0,DNP,2019-10-31,12.75,300945540.0,3.837056e+09,29923890.0,996205290.0,4.803337e+09,2019,10
DNP 2018-10-31,1,DNP,2018-10-31,10.98,293197640.0,3.219310e+09,16950540.0,996100240.0,4.198460e+09,2018,10
DNP 2017-10-31,2,DNP,2017-10-31,11.35,287493950.0,3.263056e+09,35350560.0,995005850.0,4.222712e+09,2017,10
DNP 2016-10-31,3,DNP,2016-10-31,10.04,283655070.0,2.847897e+09,27143770.0,993911430.0,3.814665e+09,2016,10
DNP 2015-10-31,4,DNP,2015-10-31,9.43,279789380.0,2.638414e+09,41105260.0,996741810.0,3.594050e+09,2015,10
...,...,...,...,...,...,...,...,...,...,...,...
SPNE 2019-12-31,0,SPNE,2019-12-31,15.01,18977000.0,2.848448e+08,20199000.0,0.0,2.646458e+08,2019,12
SPNE 2018-12-31,1,SPNE,2018-12-31,14.83,15358000.0,2.277591e+08,24233000.0,0.0,2.035261e+08,2018,12
SPNE 2017-12-31,2,SPNE,2017-12-31,10.90,12426000.0,1.354434e+08,10788000.0,0.0,1.246554e+08,2017,12
SPNE 2016-12-31,3,SPNE,2016-12-31,7.20,11222000.0,8.079840e+07,14566000.0,4280000.0,7.051240e+07,2016,12
SPNE 2015-12-31,4,SPNE,2015-12-31,14.46,11139000.0,1.610699e+08,33429000.0,328000.0,1.279689e+08,2015,12

In [182]:
ev.drop(['Unnamed: 0'],axis=1,inplace=True)

In [40]:

for index in ev.index:
    if(ev.loc[index,'Month']>3):
        ev.loc[index,'Year_corrected']=ev.loc[index,'Year']
    else:
        ev.loc[index,'Year_corrected']=ev.loc[index,'Year']-1

In [43]:
ev.drop_duplicates(subset=['Year_corrected','symbol'],keep='first',inplace=True)

In [44]:
ev['Year str']=ev['Year_corrected'].astype(str)
ev['Key_test'] = ev[['symbol', 'Year str']].apply(lambda x: ' '.join(x), axis = 1)

In [47]:
ev.drop(['Unnamed: 0'],axis=1,inplace=True)

In [48]:
ev.drop(['Year str','Key_test'],axis=1,inplace=True)

In [49]:
ev.drop(['Year'],axis=1,inplace=True)

In [50]:
ev.reset_index(inplace=True)

In [51]:
ev.drop(['Key','Month'],axis=1,inplace=True)

In [53]:
import numpy as np

In [54]:
ev.replace(to_replace=['None'], value=np.nan, inplace=True)

In [61]:
ev

,symbol,date,stockPrice,numberOfShares,marketCapitalization,minusCashAndCashEquivalents,addTotalDebt,enterpriseValue,Year_corrected
0,DNP,2019-10-31,12.75,300945540.0,3.837056e+09,29923890.0,996205290.0,4.803337e+09,2019.0
1,DNP,2018-10-31,10.98,293197640.0,3.219310e+09,16950540.0,996100240.0,4.198460e+09,2018.0
2,DNP,2017-10-31,11.35,287493950.0,3.263056e+09,35350560.0,995005850.0,4.222712e+09,2017.0
3,DNP,2016-10-31,10.04,283655070.0,2.847897e+09,27143770.0,993911430.0,3.814665e+09,2016.0
4,DNP,2015-10-31,9.43,279789380.0,2.638414e+09,41105260.0,996741810.0,3.594050e+09,2015.0
...,...,...,...,...,...,...,...,...,...
8444,SPNE,2019-12-31,15.01,18977000.0,2.848448e+08,20199000.0,0.0,2.646458e+08,2019.0
8445,SPNE,2018-12-31,14.83,15358000.0,2.277591e+08,24233000.0,0.0,2.035261e+08,2018.0
8446,SPNE,2017-12-31,10.90,12426000.0,1.354434e+08,10788000.0,0.0,1.246554e+08,2017.0
8447,SPNE,2016-12-31,7.20,11222000.0,8.079840e+07,14566000.0,4280000.0,7.051240e+07,2016.0
8448,SPNE,2015-12-31,14.46,11139000.0,1.610699e+08,33429000.0,328000.0,1.279689e+08,2015.0

In [185]:
dict99={
    'numberOfShares':'Weighted Average Shs Out',
    'marketCapitalization' : 'Market Cap',
    'enterpriseValue': 'Enterprise Value',
    'symbol':'Company Name' ,
    'Year_corrected':'Year'
    
    
    
}

In [186]:
ev.rename(columns=dict99,inplace=True)

In [187]:
ev.to_csv("null from alpha vantage/ev.csv")